
package com.logicaldoc.webservice.soap.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.logicaldoc.ws.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Auth", targetNamespace = "http://ws.logicaldoc.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Auth {


    /**
     * 
     * @param sid
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "valid", targetNamespace = "http://ws.logicaldoc.com", className = "com.logicaldoc.ws.Valid")
    @ResponseWrapper(localName = "validResponse", targetNamespace = "http://ws.logicaldoc.com", className = "com.logicaldoc.ws.ValidResponse")
    public boolean valid(
        @WebParam(name = "sid", targetNamespace = "")
        String sid);

    /**
     * 
     * @param sid
     */
    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "http://ws.logicaldoc.com", className = "com.logicaldoc.ws.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://ws.logicaldoc.com", className = "com.logicaldoc.ws.LogoutResponse")
    public void logout(
        @WebParam(name = "sid", targetNamespace = "")
        String sid);

    /**
     * 
     * @param sid
     */
    @WebMethod
    @RequestWrapper(localName = "renew", targetNamespace = "http://ws.logicaldoc.com", className = "com.logicaldoc.ws.Renew")
    @ResponseWrapper(localName = "renewResponse", targetNamespace = "http://ws.logicaldoc.com", className = "com.logicaldoc.ws.RenewResponse")
    public void renew(
        @WebParam(name = "sid", targetNamespace = "")
        String sid);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns java.lang.String
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://ws.logicaldoc.com", className = "com.logicaldoc.ws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.logicaldoc.com", className = "com.logicaldoc.ws.LoginResponse")
    public String login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws Exception
    ;

}
