
package com.logicaldoc.webservice.soap.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapAuthServiceService", targetNamespace = "http://endpoint.soap.webservice.logicaldoc.com/", wsdlLocation = "https://docs.sitav.eu/services/Auth?wsdl")
public class SoapAuthServiceService
    extends Service
{

    private final static URL SOAPAUTHSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPAUTHSERVICESERVICE_EXCEPTION;
    private final static QName SOAPAUTHSERVICESERVICE_QNAME = new QName("http://endpoint.soap.webservice.logicaldoc.com/", "SoapAuthServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://docs.sitav.eu/services/Auth?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPAUTHSERVICESERVICE_WSDL_LOCATION = url;
        SOAPAUTHSERVICESERVICE_EXCEPTION = e;
    }

    public SoapAuthServiceService() {
        super(__getWsdlLocation(), SOAPAUTHSERVICESERVICE_QNAME);
    }

    public SoapAuthServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPAUTHSERVICESERVICE_QNAME, features);
    }

    public SoapAuthServiceService(URL wsdlLocation) {
        super(wsdlLocation, SOAPAUTHSERVICESERVICE_QNAME);
    }

    public SoapAuthServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPAUTHSERVICESERVICE_QNAME, features);
    }

    public SoapAuthServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapAuthServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Auth
     */
    @WebEndpoint(name = "SoapAuthServicePort")
    public Auth getSoapAuthServicePort() {
        return super.getPort(new QName("http://endpoint.soap.webservice.logicaldoc.com/", "SoapAuthServicePort"), Auth.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Auth
     */
    @WebEndpoint(name = "SoapAuthServicePort")
    public Auth getSoapAuthServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.soap.webservice.logicaldoc.com/", "SoapAuthServicePort"), Auth.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPAUTHSERVICESERVICE_EXCEPTION!= null) {
            throw SOAPAUTHSERVICESERVICE_EXCEPTION;
        }
        return SOAPAUTHSERVICESERVICE_WSDL_LOCATION;
    }

}
