
package com.logicaldoc.enterprise.webservice.soap.endpoint;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.logicaldoc.ws.ObjectFactory;
import com.logicaldoc.ws.WSCriterion;
import com.logicaldoc.ws.WSDocument;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EnterpriseSearch", targetNamespace = "http://ws.logicaldoc.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnterpriseSearch {


    /**
     * 
     * @param criteria
     * @param maxResults
     * @param templateId
     * @param sid
     * @return
     *     returns java.util.List<com.logicaldoc.ws.WSDocument>
     * @throws Exception
     */
    @WebMethod
    @WebResult(name = "hit", targetNamespace = "")
    @RequestWrapper(localName = "findByParameters", targetNamespace = "http://ws.logicaldoc.com", className = "com.logicaldoc.ws.FindByParameters")
    @ResponseWrapper(localName = "findByParametersResponse", targetNamespace = "http://ws.logicaldoc.com", className = "com.logicaldoc.ws.FindByParametersResponse")
    public List<WSDocument> findByParameters(
        @WebParam(name = "sid", targetNamespace = "")
        String sid,
        @WebParam(name = "templateId", targetNamespace = "")
        Long templateId,
        @WebParam(name = "criteria", targetNamespace = "")
        List<WSCriterion> criteria,
        @WebParam(name = "maxResults", targetNamespace = "")
        int maxResults)
        throws Exception
    ;

}
