
package com.logicaldoc.enterprise.webservice.soap.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapEnterpriseSearchServiceService", targetNamespace = "http://endpoint.soap.webservice.enterprise.logicaldoc.com/", wsdlLocation = "https://docs.sitav.eu/services/EnterpriseSearch/wsCriterion?wsdl")
public class SoapEnterpriseSearchServiceService
    extends Service
{

    private final static URL SOAPENTERPRISESEARCHSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPENTERPRISESEARCHSERVICESERVICE_EXCEPTION;
    private final static QName SOAPENTERPRISESEARCHSERVICESERVICE_QNAME = new QName("http://endpoint.soap.webservice.enterprise.logicaldoc.com/", "SoapEnterpriseSearchServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://docs.sitav.eu/services/EnterpriseSearch/wsCriterion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPENTERPRISESEARCHSERVICESERVICE_WSDL_LOCATION = url;
        SOAPENTERPRISESEARCHSERVICESERVICE_EXCEPTION = e;
    }

    public SoapEnterpriseSearchServiceService() {
        super(__getWsdlLocation(), SOAPENTERPRISESEARCHSERVICESERVICE_QNAME);
    }

    public SoapEnterpriseSearchServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPENTERPRISESEARCHSERVICESERVICE_QNAME, features);
    }

    public SoapEnterpriseSearchServiceService(URL wsdlLocation) {
        super(wsdlLocation, SOAPENTERPRISESEARCHSERVICESERVICE_QNAME);
    }

    public SoapEnterpriseSearchServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPENTERPRISESEARCHSERVICESERVICE_QNAME, features);
    }

    public SoapEnterpriseSearchServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapEnterpriseSearchServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EnterpriseSearch
     */
    @WebEndpoint(name = "SoapEnterpriseSearchServicePort")
    public EnterpriseSearch getSoapEnterpriseSearchServicePort() {
        return super.getPort(new QName("http://endpoint.soap.webservice.enterprise.logicaldoc.com/", "SoapEnterpriseSearchServicePort"), EnterpriseSearch.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnterpriseSearch
     */
    @WebEndpoint(name = "SoapEnterpriseSearchServicePort")
    public EnterpriseSearch getSoapEnterpriseSearchServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.soap.webservice.enterprise.logicaldoc.com/", "SoapEnterpriseSearchServicePort"), EnterpriseSearch.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPENTERPRISESEARCHSERVICESERVICE_EXCEPTION!= null) {
            throw SOAPENTERPRISESEARCHSERVICESERVICE_EXCEPTION;
        }
        return SOAPENTERPRISESEARCHSERVICESERVICE_WSDL_LOCATION;
    }

}
